scheduler.settings:
  type: mapping
  label: 'Scheduler settings'
  mapping:
    allow_date_only:
      type: boolean
    date_format:
      type: string
    date_only_format:
      type: string
    date_popup_minute_increment:
      type: integer
    default_time:
      type: string
    extra_info:
      type: string
    field_type:
      type: string
    lightweight_cron_access_key:
      type: string
    log:
      type: boolean
    time_only_format:
      type: string

node_type.third_party.scheduler:
  type: mapping
  label: 'Scheduler content type settings'
  mapping:
    publish_enable:
      type: boolean
      label: 'Enable scheduled publishing'
    publish_past_date:
      type: string
      label: 'Action to be taken for publication dates in the past'
    publish_required:
      type: boolean
      label: 'Require scheduled publishing'
    publish_revision:
      type: boolean
      label: 'Create a new revision on publishing'
    publish_touch:
      type: boolean
      label: 'Change content creation time to match the scheduled publish time'
    unpublish_enable:
      type: boolean
      label: 'Enable scheduled unpublishing'
    unpublish_required:
      type: boolean
      label: 'Require scheduled unpublishing'
    unpublish_revision:
      type: boolean
      label: 'Create a new revision on unpublishing'
